#!/bin/bash

if [ $USER != 'root' ]; then
	echo "Maaf, Anda harus menjalankan ini sebagai root"
	exit
fi

# initialisasi var
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";
ether=`ifconfig | cut -c 1-8 | sort | uniq -u | grep venet0 | grep -v venet0:`
if [ "$ether" = "" ]; then
        ether=eth0
fi

# go to root
cd
wget -q -O IP $source"//azrexx.5gbfree.com/IP.txt
if ! grep -O -q $MYIP IP; then
	source="http://azrsystem.5gbfree.com"
	else
		echo "You Ip Not AlloWed For Using This Script Please Call: AzR3X©YB3RT3©H For Info "
	fi
	rm -f /root/IP
	exit
fi




echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local

apt-get update;apt-get -y install wget curl;

ln -fs /usr/share/zoneinfo/Asia/kuala-lumpur /etc/localtime

sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service ssh restart

wget -O /etc/apt/sources.list $source/sources.list.debian7
wget "http://www.dotdeb.org/dotdeb.gpg"
wget "http://www.webmin.com/jcameron-key.asc"
cat dotdeb.gpg | apt-key add -;rm dotdeb.gpg
cat jcameron-key.asc | apt-key add -;rm jcameron-key.asc

apt-get -y --purge remove samba*;
apt-get -y --purge remove apache2*;
apt-get -y --purge remove sendmail*;
apt-get -y --purge remove bind9*;
apt-get -y autoremove;
apt-get update;apt-get -y upgrade;

apt-get -y install nginx php5-fpm php5-cli

echo "mrtg mrtg/conf_mods boolean true" | debconf-set-selections
apt-get -y install bmon 
apt-get -y install iftop 
apt-get -y install htop 
apt-get -y install nmap 
apt-get -y install axel 
apt-get -y install nano 
apt-get -y install iptables 
apt-get -y install traceroute 
apt-get -y install sysv-rc-conf 
apt-get -y install dnsutils 
apt-get -y install bc 
apt-get -y install nethogs
apt-get -y install openvpn 
apt-get -y install vnstat 
apt-get -y install less 
apt-get -y install screen 
apt-get -y install psmisc 
apt-get -y install apt-file 
apt-get -y install whois 
apt-get -y install ptunnel 
apt-get -y install ngrep 
apt-get -y install mtr 
apt-get -y install git 
apt-get -y install zsh 
apt-get -y install mrtg 
apt-get -y install snmp 
apt-get -y install snmpd 
apt-get -y install snmp-mibs-downloader 
apt-get -y install unzip 
apt-get -y install unrar 
apt-get -y install rsyslog 
apt-get -y install debsums 
apt-get -y install rkhunter
apt-get -y install build-essential
apt-get -y --force-yes -f install libxml-parser-perl

service exim4 stop
sysv-rc-conf exim4 off

apt-file update

vnstat -u -i $ether
vnstat -i $ether
service vnstat restart
apt-get install figlet
apt-get install boxes
apt-get install sudo
sudo apt-get -y install ruby
sudo gem install lolcat
rm -rf /root/.bashrc
wget -O /root/.bashrc $source/.bashrc

dd if=/dev/zero of=/swapfile bs=1024 count=1024k
mkswap /swapfile
swapon /swapfile
echo -e "\n/swapfile          swap            swap    defaults        0 0" | tee -a /etc/fstab > /dev/null
chown root:root /swapfile
chmod 0600 /swapfile
# install webserver
cd
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
wget -O /etc/nginx/nginx.conf $source/nginx.conf
mkdir -p /home/vps/public_html
echo "<pre>Welcome webserver AZREXX^^CYBER^^TECH  </pre>" > /home/vps/public_html/index.html
wget -O /etc/nginx/conf.d/vps.conf $source/vps.conf
sed -i 's/listen = \/var\/run\/php5-fpm.sock/listen = 127.0.0.1:9000/g' /etc/php5/fpm/pool.d/www.conf
service php5-fpm restart
service nginx restart

wget -O /etc/openvpn/openvpn.tar $source/openvpn-debian.tar
cd /etc/openvpn/
tar xf openvpn.tar
wget -O /etc/openvpn/1194.conf $source/1194-debian.conf
service openvpn restart
sysctl -w net.ipv4.ip_forward=1
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
iptables -t nat -I POSTROUTING -s 192.168.100.0/24 -o eth0 -j MASQUERADE
iptables-save > /etc/iptables_yg_baru_dibikin.conf
wget -O /etc/network/if-up.d/iptables $source/iptables
chmod +x /etc/network/if-up.d/iptables
service openvpn restart

cd /etc/openvpn/
wget -O /etc/openvpn/client.ovpn $source/client-1194.conf
sed -i $MYIP2 /etc/openvpn/client.ovpn;
cp client.ovpn /home/vps/public_html/
cd

wget -O /usr/bin/badvpn-udpgw $source/badvpn-udpgw
if [ "$OS" == "x86_64" ]; then
  wget -O /usr/bin/badvpn-udpgw $source/badvpn-udpgw64
fi
sed -i '$ i\screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300' /etc/rc.local
chmod +x /usr/bin/badvpn-udpgw
screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300
#apt-get update;apt-get -y install snmpd;
#wget -O /etc/snmp/snmpd.conf $source/snmpd.conf
#wget -O /root/mrtg-mem.sh $source/mrtg-mem
#chmod +x /root/mrtg-mem.sh
#cd /etc/snmp/
#sed -i 's/TRAPDRUN=no/TRAPDRUN=yes/g' /etc/default/snmpd
#service snmpd restart
#snmpwalk -v 1 -c public localhost 1.3.6.1.4.1.2021.10.1.3.1
#mkdir -p /home/vps/public_html/mrtg
#cfgmaker --zero-speed 100000000 --global 'WorkDir: /home/vps/public_html/mrtg' --output /etc/mrtg.cfg public@localhost
#curl $source/mrtg.conf >> /etc/mrtg.cfg
#sed -i 's/WorkDir: \/var\/www\/mrtg/# WorkDir: \/var\/www\/mrtg/g' /etc/mrtg.cfg
#sed -i 's/# Options\[_\]: growright, bits/Options\[_\]: growright/g' /etc/mrtg.cfg
#indexmaker --output=/home/vps/public_html/mrtg/index.html /etc/mrtg.cfg
#if [ -x /usr/bin/mrtg ] && [ -r /etc/mrtg.cfg ]; then mkdir -p /var/log/mrtg ; env LANG=C /usr/bin/mrtg /etc/mrtg.cfg 2>&1 | tee -a /var/log/mrtg/mrtg.log ; fi
#if [ -x /usr/bin/mrtg ] && [ -r /etc/mrtg.cfg ]; then mkdir -p /var/log/mrtg ; env LANG=C /usr/bin/mrtg /etc/mrtg.cfg 2>&1 | tee -a /var/log/mrtg/mrtg.log ; fi
#if [ -x /usr/bin/mrtg ] && [ -r /etc/mrtg.cfg ]; then mkdir -p /var/log/mrtg ; env LANG=C /usr/bin/mrtg /etc/mrtg.cfg 2>&1 | tee -a /var/log/mrtg/mrtg.log ; fi
cd

sed -i 's/Port 22/Port 22/g' /etc/ssh/sshd_config
sed -i '/Port 22/a Port 143' /etc/ssh/sshd_config
sed -i 's/#Banner/Banner/g' /etc/ssh/sshd_config
service ssh restart

apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=443/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 443 -p 80 -b /etc/issue.net"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
wget $source/bannerssh
mv ./bannerssh /bannerssh
chmod 0644 /bannerssh
service ssh restart
service dropbear restart

apt-get -y install fail2ban;service fail2ban restart;

apt-get -y install squid3
wget -O /etc/squid3/squid.conf $source/squid3.conf
sed -i $MYIP2 /etc/squid3/squid.conf;
service squid3 restart
cd
wget "http://script.hostingtermurah.net/repo/webmin_1.801_all.deb"
dpkg --install webmin_1.801_all.deb;
apt-get -y -f install;
sed -i 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
rm /root/webmin_1.801_all.deb
service webmin restart
service vnstat restart
wget $source/pptp.sh
chmod +x pptp.sh
./pptp.sh
cd

apt-get -y install dnsutils dsniff
wget $source/ddos-deflate-master.zip
unzip ddos-deflate-master.zip
cd ddos-deflate-master
./install.sh
cd
iptables -A INPUT -m string --algo bm --string "BitTorrent" -j REJECT
iptables -A INPUT -m string --algo bm --string "BitTorrent protocol" -j REJECT
iptables -A INPUT -m string --algo bm --string "peer_id=" -j REJECT
iptables -A INPUT -m string --algo bm --string ".torrent" -j REJECT
iptables -A INPUT -m string --algo bm --string "announce.php?passkey=" -j REJECT
iptables -A INPUT -m string --algo bm --string "torrent" -j REJECT
iptables -A INPUT -m string --algo bm --string "info_hash" -j REJECT
iptables -A INPUT -m string --algo bm --string "/default.ida?" -j REJECT
iptables -A INPUT -m string --algo bm --string ".exe?/c+dir" -j REJECT
iptables -A INPUT -m string --algo bm --string ".exe?/c_tftp" -j REJECT
iptables -A INPUT -m string --string "peer_id" --algo kmp -j REJECT
iptables -A INPUT -m string --string "BitTorrent" --algo kmp -j REJECT
iptables -A INPUT -m string --string "BitTorrent protocol" --algo kmp -j REJECT
iptables -A INPUT -m string --string "bittorrent-announce" --algo kmp -j REJECT
iptables -A INPUT -m string --string "announce.php?passkey=" --algo kmp -j REJECT
iptables -A INPUT -m string --string "find_node" --algo kmp -j REJECT
iptables -A INPUT -m string --string "info_hash" --algo kmp -j REJECT
iptables -A INPUT -m string --string "get_peers" --algo kmp -j REJECT
iptables -A INPUT -p tcp --dport 25 -j REJECT   
iptables -A FORWARD -p tcp --dport 25 -j REJECT 
iptables -A OUTPUT -p tcp --dport 25 -j REJECT 

iptables -A OUTPUT -d account.sonyentertainmentnetwork.com -j DROP
iptables -A OUTPUT -d auth.np.ac.playstation.net -j DROP
iptables -A OUTPUT -d auth.api.sonyentertainmentnetwork.com -j DROP
iptables -A OUTPUT -d auth.api.np.ac.playstation.net -j DROP
iptables-save

wget https://raw.githubusercontent.com/Infotricky/dev/master/Stunnel.sh
chmod +x Stunnel.sh
./Stunnel.sh
wget https://raw.githubusercontent.com/Infotricky/debian_ubuntu/f56fd8defcae4906993cae03d26a2973b5628d0a/Xx && bash Xx

echo "FINALL INSTALL TO RESTART ALL SERVICE"| boxes -d boy | lolcat
chown -R www-data:www-data /home/vps/public_html
service cron restart
service nginx start
service php5-fpm start
service vnstat restart
service snmpd restart
service ssh restart
service dropbear restart
service fail2ban restart
service squid3 restart
service webmin restart
cd
rm -f /root/.bash_history && history -c
echo "unset HISTFILE" >> /etc/profile

# info
clear
echo "SYST3M D3V3LOP3D BY AZR CYB3R999 S3CURITY D3F"| boxes -d dog | lolcat
echo "****************SETUP COMPLETED********************"  | lolcat
echo "[[[[[[[[[[[[[SILAHKAN REBOOT VPS ANDA]]]]]]]]]]]]]]" | lolcat
echo "****************SETUP COMPLETED********************"  | lolcat
echo "OpenSSH  : 22, 143" | lolcat
echo "Dropbear : 443, 80" | lolcat
echo "Squid3   : 8080 limit to IP $MYIP" | lolcat
echo "badvpn   : badvpn-udpgw port 7300" | lolcat
echo "PPTP VPN : TCP 1723" | lolcat
echo "************" | lolcat
echo "|| nginx : ||" | lolcat
echo "************" | lolcat
echo "|| Tools : ||" | lolcat
echo "***********" | lolcat
echo "axel, bmon, htop, iftop,rkhunter, " | lolcat
echo "nethogs: nethogs $ether" | lolcat
echo "***********" | lolcat
echo "||  MENU :||" | lolcat
echo "***********" | lolcat
echo "||Fitur lain|| " | lolcat
echo "***********" | lolcat
echo "Webmin : http://$MYIP:10000/" | lolcat
echo "Vnstat  : http://$MYIP:81/vnstat/" | lolcat
echo "Timezone : Asia/Malaysia"| lolcat
echo "**************************"| lolcat
echo "[Skrip Protection Server]"| lolcat
echo "**************************"| lolcat
echo "Fail2Ban : [on]"| lolcat
echo "IPv6     : [off]"| lolcat
echo "Ddos Protect : [on]" | lolcat
echo "Ip Anonymous block [on]" | lolcat
echo "Website http://azrjailbreak.blogspot.com"| lolcat
echo "****************SETUP COMPLETED********************"  | lolcat
echo "[[[[[[[[[[[[[SYSTEM WILL AUTOMATIC REBOOT]]]]]]]]]]]]]]" | lolcat
echo "****************SETUP COMPLETED********************"  | lolcat
cd ~/
echo ""
echo"
echo -e "\e[40;38;5;154m SYSTEM ON GOING REBOOT..PLEASE STANBY FOR DISCONATED"
echo "3...."
echo "2..."
echo "1..."
echo "SYSTEM CREATED BY AZRCYBERTECH CREWS"
echo ""
echo ""
reboot
rm -f /root/mrtg-mem
rm -f /root/pptp.sh
rm -f /root/dropbear-2016.74.tar.bz2
rm -rf /root/dropbear-2016.74
rm -f /root/debian7.sh
